-- ═══════════════════════════════════════════════════════════════
--  Charles — Employee Profiles
--  Supabase Production Setup Script
--  Run this in: Supabase Dashboard → SQL Editor → New Query
-- ═══════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS employee_profiles (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id        TEXT NOT NULL UNIQUE,
  full_name          TEXT NOT NULL,
  department         TEXT,
  email              TEXT,
  phone              TEXT,
  profile_image_url  TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Auto-update updated_at on row updates
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_employee_profiles_updated_at ON employee_profiles;
CREATE TRIGGER set_employee_profiles_updated_at
BEFORE UPDATE ON employee_profiles
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

-- Helpful lookup index
CREATE INDEX IF NOT EXISTS employee_profiles_employee_id_idx
  ON employee_profiles (employee_id);

-- Enable RLS (service role bypasses; postgres user may bypass depending on your connection user)
ALTER TABLE employee_profiles ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to allow re-running this script cleanly
DROP POLICY IF EXISTS "service_role_full_access" ON employee_profiles;

-- Service role has full access
CREATE POLICY "service_role_full_access" ON employee_profiles
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Verify
SELECT
  schemaname,
  tablename,
  rowsecurity AS rls_enabled
FROM pg_tables
WHERE tablename = 'employee_profiles';

SELECT
  policyname,
  cmd,
  roles
FROM pg_policies
WHERE tablename = 'employee_profiles'
ORDER BY policyname;

